### ISSUE TITLE
Error while unpickling Word2Vec

### ISSUE THREAD

**Issue by geekSiddharth** [nmt4binaries/nmt4binaries.github.io#2]
Unable to load the given word2vec models. 

Error trace:
```
/download> python smodel.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "smodel.py", line 21, in <module>
    model = models.Word2Vec.load('100D_MinWordCount0_downSample1e-5_trained100epoch_L.w2v')
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/word2vec.py", line 1276, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/base_any2vec.py", line 1101, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/base_any2vec.py", line 483, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gensim/utils.py", line 419, in load
    obj = unpickle(fname)
  File "/usr/local/lib/python3.5/dist-packages/gensim/utils.py", line 1358, in unpickle
    return _pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```
I'm using gensim 3.5.0 and python 3.5.2.

**Comment by geekSiddharth** [comment]
Sorry! I trying to unpickle a .zip file. :see_no_evil:
